const quoteData = {
    quotes: {
        "English": [
            { text: "To be or not to be, that is the question.", translation: null },
            { text: "I think, therefore I am.", translation: null },
            { text: "Stay hungry, stay foolish.", translation: null },
            { text: "The only way to do great work is to love what you do.", translation: null },
            { text: "Be the change you wish to see in the world.", translation: null },
            { text: "Life is what happens to you while you're busy making other plans.", translation: null },
            { text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", translation: null },
            { text: "The future belongs to those who believe in the beauty of their dreams.", translation: null },
            { text: "Strive not to be a success, but rather to be of value.", translation: null },
            { text: "Two roads diverged in a wood, and I—I took the one less traveled by.", translation: null },
            { text: "I have a dream that one day this nation will rise up and live out the true meaning of its creed.", translation: null },
            { text: "Ask not what your country can do for you – ask what you can do for your country.", translation: null },
            { text: "The only thing we have to fear is fear itself.", translation: null },
            { text: "Imagination is more important than knowledge.", translation: null },
            { text: "I have not failed. I've just found 10,000 ways that won't work.", translation: null },
            { text: "It is during our darkest moments that we must focus to see the light.", translation: null },
            { text: "Whoever is happy will make others happy too.", translation: null },
            { text: "Do what you can, with what you have, where you are.", translation: null },
            { text: "The purpose of our lives is to be happy.", translation: null },
            { text: "Get busy living or get busy dying.", translation: null }
        ],
        "Telugu": [
        { text: "చదువు సంపద కొరకు, విద్య విజ్ఞానం కొరకు", translation: "Study for wealth, education for knowledge." },
        { text: "తల్లిదండ్రులు లేని ఇల్లు తలుపులు లేని గుడి", translation: "A house without parents is like a temple without doors." },
        { text: "ఆలస్యం అమృతం విషం", translation: "Delay is nectar turned poison." },
        { text: "అన్నం పరబ్రహ్మ స్వరూపం", translation: "Food is the embodiment of the divine." },
        { text: "తొందరపాటు పని తప్పుల పాలు", translation: "Hasty work leads to mistakes." },
        { text: "నీతి నిజాయితీ ఉన్నవాడే నిజమైన మనిషి", translation: "One with ethics and honesty is a true human." },
        { text: "ఒకరి కష్టంలో మరొకరి సుఖం", translation: "One's hardship is another's happiness." },
        { text: "పెద్దల మాట పాడిపంట", translation: "The words of elders bring prosperity." },
        { text: "చెట్టు నీడన చల్లగా కూర్చోవచ్చు, కానీ చెట్టే నీడ కావాలంటే కష్టపడాలి", translation: "You can sit coolly under a tree's shade, but to be the shade, you must endure hardship." },
        { text: "మంచి చేస్తే మంచి జరుగుతుంది", translation: "Do good and good will happen." },
        { text: "నిప్పు లేనిదే పొగ రాదు", translation: "There's no smoke without fire." },
        { text: "నిజాయితీ గల వ్యక్తి నిత్యం ఆనందంగా ఉంటాడు", translation: "An honest person is always happy." },
        { text: "కష్టపడితే కలలు నిజమవుతాయి", translation: "Hard work makes dreams come true." },
        { text: "తెలివితేటలు ఉన్నవాడు తప్పులు చేయడు", translation: "A wise person doesn't make mistakes." },
        { text: "మౌనమే మంచి మందు", translation: "Silence is the best medicine." },
        { text: "ఆరోగ్యమే మహాభాగ్యం", translation: "Health is the greatest wealth." },
        { text: "ఏ పనైనా శ్రద్ధగా చేయాలి", translation: "Whatever work you do, do it with dedication." },
        { text: "సహనమే జీవితానికి సంజీవిని", translation: "Patience is the elixir of life." },
        { text: "మాటలు వినాలి, మంచివి మాత్రమే నమ్మాలి", translation: "Listen to words, but believe only the good ones." },
        { text: "అందరూ ఒకటే అనుకుంటే అదే నిజం", translation: "If everyone thinks the same, it becomes the truth." }
    ],
        "Spanish": [
            { text: "En boca cerrada no entran moscas.", translation: "Flies don't enter a closed mouth." },
            { text: "El que la sigue la consigue.", translation: "He who follows it, achieves it." },
            { text: "Más vale tarde que nunca.", translation: "Better late than never." },
            { text: "Al mal tiempo, buena cara.", translation: "In bad weather, a good face." },
            { text: "Dime con quién andas y te diré quién eres.", translation: "Tell me who you walk with and I'll tell you who you are." },
            { text: "No hay mal que por bien no venga.", translation: "There's no bad that doesn't bring some good." },
            { text: "A caballo regalado no le mires el diente.", translation: "Don't look a gift horse in the mouth." },
            { text: "El que mucho abarca, poco aprieta.", translation: "He who grasps too much, holds little firmly." },
            { text: "Amor con hambre no dura.", translation: "Love with hunger doesn't last." },
            { text: "Cada loco con su tema.", translation: "To each his own." },
            { text: "Del dicho al hecho hay mucho trecho.", translation: "Easier said than done." },
            { text: "En casa de herrero, cuchillo de palo.", translation: "In the blacksmith's house, a wooden knife." },
            { text: "La curiosidad mató al gato.", translation: "Curiosity killed the cat." },
            { text: "Más sabe el diablo por viejo que por diablo.", translation: "The devil knows more from being old than from being the devil." },
            { text: "No por mucho madrugar amanece más temprano.", translation: "No matter how early you get up, it won't dawn any sooner." },
            { text: "Ojos que no ven, corazón que no siente.", translation: "What the eyes don't see, the heart doesn't feel." },
            { text: "Quien calla, otorga.", translation: "Silence implies consent." },
            { text: "Sobre gustos no hay nada escrito.", translation: "There's no accounting for taste." },
            { text: "Una golondrina no hace verano.", translation: "One swallow doesn't make a summer." },
            { text: "Zapatero a tus zapatos.", translation: "Cobbler, stick to your last." }
        ],
        "French": [
            { text: "Je pense, donc je suis.", translation: "I think, therefore I am." },
            { text: "La vie est belle.", translation: "Life is beautiful." },
            { text: "L'amour est aveugle.", translation: "Love is blind." },
            { text: "Après la pluie, le beau temps.", translation: "After the rain, good weather." },
            { text: "Qui vivra verra.", translation: "Who will live will see." },
            { text: "Chacun voit midi à sa porte.", translation: "Everyone sees noon at his own door." },
            { text: "Il faut tourner sa langue sept fois dans sa bouche avant de parler.", translation: "One should turn their tongue seven times in their mouth before speaking." },
            { text: "Petit à petit, l'oiseau fait son nid.", translation: "Little by little, the bird makes its nest." },
            { text: "L'habit ne fait pas le moine.", translation: "The habit doesn't make the monk." },
            { text: "Mieux vaut prévenir que guérir.", translation: "Better to prevent than to heal." },
            { text: "Quand on parle du loup, on en voit la queue.", translation: "Speak of the wolf and you'll see its tail." },
            { text: "Il n'y a pas de fumée sans feu.", translation: "There's no smoke without fire." },
            { text: "À bon chat, bon rat.", translation: "To a good cat, a good rat." },
            { text: "C'est en forgeant qu'on devient forgeron.", translation: "It's by forging that one becomes a blacksmith." },
            { text: "Qui se ressemble s'assemble.", translation: "Birds of a feather flock together." },
            { text: "Il faut battre le fer pendant qu'il est chaud.", translation: "Strike while the iron is hot." },
            { text: "Le temps, c'est de l'argent.", translation: "Time is money." },
            { text: "Tout vient à point à qui sait attendre.", translation: "Everything comes in time to those who can wait." },
            { text: "Les bons comptes font les bons amis.", translation: "Good accounting makes good friends." },
            { text: "On ne fait pas d'omelette sans casser des œufs.", translation: "You can't make an omelette without breaking eggs." }
        ],
        "German": [
            { text: "Denken ist schwer, darum urteilen die meisten.", translation: "Thinking is difficult, that's why most people judge." },
            { text: "Wer kämpft, kann verlieren. Wer nicht kämpft, hat schon verloren.", translation: "Who fights can lose. Who doesn't fight has already lost." },
            { text: "Man sieht nur mit dem Herzen gut.", translation: "One sees clearly only with the heart." },
            { text: "Der Weg ist das Ziel.", translation: "The way is the goal." },
            { text: "Was uns nicht umbringt, macht uns stärker.", translation: "What doesn't kill us makes us stronger." },
            { text: "Übung macht den Meister.", translation: "Practice makes perfect." },
            { text: "Wer zuletzt lacht, lacht am besten.", translation: "He who laughs last laughs best." },
            { text: "Morgenstund hat Gold im Mund.", translation: "The morning hour has gold in its mouth." },
            { text: "Aller Anfang ist schwer.", translation: "All beginnings are difficult." },
            { text: "Ende gut, alles gut.", translation: "All's well that ends well." },
            { text: "Wie man in den Wald hineinruft, so schallt es heraus.", translation: "As you shout into the forest, so it echoes back." },
            { text: "Wer nicht wagt, der nicht gewinnt.", translation: "Nothing ventured, nothing gained." },
            { text: "Kleinvieh macht auch Mist.", translation: "Even small animals produce manure." },
            { text: "Viele Köche verderben den Brei.", translation: "Too many cooks spoil the broth." },
            { text: "Alte Liebe rostet nicht.", translation: "Old love doesn't rust." },
            { text: "Aus den Augen, aus dem Sinn.", translation: "Out of sight, out of mind." },
            { text: "Geld allein macht nicht glücklich.", translation: "Money alone doesn't make you happy." },
            { text: "Wer anderen eine Grube gräbt, fällt selbst hinein.", translation: "He who digs a pit for others falls in himself." },
            { text: "Die Zeit heilt alle Wunden.", translation: "Time heals all wounds." },
            { text: "Gut Ding will Weile haben.", translation: "Good things take time." }
        ],
        // Add these to your existing quoteData object
"Italian": [
    { text: "La vita è troppo breve per bere vini mediocri.", translation: "Life is too short to drink bad wine." },
    { text: "Veni, vidi, vici.", translation: "I came, I saw, I conquered." },
    { text: "L'amore vince sempre.", translation: "Love always wins." },
    { text: "La semplicità è l'ultima sofisticazione.", translation: "Simplicity is the ultimate sophistication." },
    { text: "Tutto viene a chi sa aspettare.", translation: "Everything comes to those who know how to wait." },
    { text: "Chi dorme non piglia pesci.", translation: "Who sleeps doesn't catch fish." },
    { text: "Il lupo perde il pelo ma non il vizio.", translation: "The wolf loses its fur but not its habits." },
    { text: "Traduttore, traditore.", translation: "Translator, traitor." },
    { text: "Tra il dire e il fare c'è di mezzo il mare.", translation: "Between saying and doing there's the sea in between." },
    { text: "L'erba del vicino è sempre più verde.", translation: "The neighbor's grass is always greener." },
    { text: "Chi va piano, va sano e va lontano.", translation: "Who goes slowly, goes safely and goes far." },
    { text: "A caval donato non si guarda in bocca.", translation: "Don't look a gift horse in the mouth." },
    { text: "Il mattino ha l'oro in bocca.", translation: "The morning has gold in its mouth." },
    { text: "Paese che vai, usanza che trovi.", translation: "When in Rome, do as the Romans do." },
    { text: "Una mela al giorno toglie il medico di torno.", translation: "An apple a day keeps the doctor away." },
    { text: "Meglio tardi che mai.", translation: "Better late than never." },
    { text: "L'abito non fa il monaco.", translation: "The habit doesn't make the monk." },
    { text: "Non tutte le ciambelle riescono col buco.", translation: "Not all doughnuts come out with a hole." },
    { text: "Can che abbaia non morde.", translation: "A barking dog doesn't bite." },
    { text: "La gatta frettolosa ha fatto i gattini ciechi.", translation: "The hasty cat gave birth to blind kittens." }
],
"Japanese": [
    { text: "猿も木から落ちる", translation: "Even monkeys fall from trees." },
    { text: "七転び八起き", translation: "Fall down seven times, get up eight." },
    { text: "花より団子", translation: "Dumplings rather than flowers." },
    { text: "石の上にも三年", translation: "Three years on a stone." },
    { text: "一期一会", translation: "One lifetime, one encounter." },
    { text: "井の中の蛙大海を知らず", translation: "A frog in a well does not know the great sea." },
    { text: "出る杭は打たれる", translation: "The nail that sticks out gets hammered down." },
    { text: "上手の手から水が漏れる", translation: "Water leaks from the hand of even a skilled person." },
    { text: "猫に小判", translation: "Gold coins to a cat." },
    { text: "温故知新", translation: "Learn from the past to understand the new." },
    { text: "三人寄れば文殊の知恵", translation: "Three people together have the wisdom of Manjusri." },
    { text: "縁の下の力持ち", translation: "A supporter behind the scenes." },
    { text: "青は藍より出でて藍より青し", translation: "The student surpasses the master." },
    { text: "蓼食う虫も好き好き", translation: "There's no accounting for taste." },
    { text: "塵も積もれば山となる", translation: "Dust, if piled up, will become a mountain." },
    { text: "善は急げ", translation: "Strike while the iron is hot." },
    { text: "過ぎたるは及ばざるが如し", translation: "Too much is the same as not enough." },
    { text: "切れ物に怪我の功名なし", translation: "There's no honor in injuring yourself with a sharp object." },
    { text: "渡る世間に鬼はない", translation: "There are no demons in the world we live in." },
    { text: "朱に交われば赤くなる", translation: "If you touch vermilion, you'll be stained red." }
],
"Russian": [
    { text: "Век живи, век учись.", translation: "Live for a century, learn for a century." },
    { text: "Лучше поздно, чем никогда.", translation: "Better late than never." },
    { text: "Тише едешь, дальше будешь.", translation: "The quieter you go, the further you'll get." },
    { text: "Без труда не вытащишь и рыбку из пруда.", translation: "Without effort, you can't pull a fish out of a pond." },
    { text: "Кто не рискует, тот не пьет шампанского.", translation: "Who doesn't take risks, doesn't drink champagne." },
    { text: "Слово — серебро, молчание — золото.", translation: "Speech is silver, silence is golden." },
    { text: "Старый друг лучше новых двух.", translation: "An old friend is better than two new ones." },
    { text: "Любовь зла, полюбишь и козла.", translation: "Love is evil, you might fall in love with a goat." },
    { text: "Не имей сто рублей, а имей сто друзей.", translation: "Don't have a hundred rubles, have a hundred friends." },
    { text: "Дорога ложка к обеду.", translation: "A spoon is dear when lunch time is near." },
    { text: "Первый блин комом.", translation: "The first pancake is always lumpy." },
    { text: "Яблоко от яблони недалеко падает.", translation: "The apple doesn't fall far from the tree." },
    { text: "Под лежачий камень вода не течёт.", translation: "Water doesn't flow under a lying stone." },
    { text: "Не всё то золото, что блестит.", translation: "All that glitters is not gold." },
    { text: "Повторение — мать учения.", translation: "Repetition is the mother of learning." },
    { text: "В гостях хорошо, а дома лучше.", translation: "It's good to visit, but better at home." },
    { text: "На вкус и цвет товарищей нет.", translation: "There's no accounting for taste." },
    { text: "Делу время, потехе час.", translation: "Time for business, hour for fun." },
    { text: "Не откладывай на завтра то, что можно сделать сегодня.", translation: "Don't put off until tomorrow what you can do today." },
    { text: "Лучше синица в руках, чем журавль в небе.", translation: "Better a tit in the hand than a crane in the sky." }
],
"Hindi": [
    { text: "जो डर गया, वो मर गया।", translation: "One who gets scared, dies." },
    { text: "करत करत अभ्यास के जड़मति होत सुजान।", translation: "With practice, even a fool becomes wise." },
    { text: "जहाँ चाह वहाँ राह।", translation: "Where there's a will, there's a way." },
    { text: "अतिथि देवो भव:", translation: "The guest is equivalent to God." },
    { text: "विद्या धनं सर्व धनं प्रधानम्।", translation: "Knowledge is the supreme wealth." },
    { text: "जैसी करनी वैसी भरनी।", translation: "As you sow, so shall you reap." },
    { text: "एक अनार सौ बीमार।", translation: "One pomegranate, hundred sick people." },
    { text: "आप भले तो जग भला।", translation: "If you are good, the world is good." },
    { text: "जान है तो जहान है।", translation: "If there's life, there's the world." },
    { text: "बोये पेड़ बबूल का तो आम कहाँ से होय।", translation: "If you sow a babul tree, how can you get mangoes?" },
    { text: "जो गरजते हैं, वो बरसते नहीं।", translation: "Those who thunder don't rain." },
    { text: "नाच न जाने आँगन टेढ़ा।", translation: "One who can't dance blames the courtyard." },
    { text: "धोबी का कुत्ता घर का न घाट का।", translation: "The washerman's dog belongs neither to the home nor to the washing-place." },
    { text: "अंधों में काना राजा।", translation: "In the land of the blind, the one-eyed man is king." },
    { text: "दूर के ढोल सुहावने लगते हैं।", translation: "Distant drums sound pleasant." },
    { text: "जल में रहकर मगर से बैर ठीक नहीं।", translation: "It's not wise to be enemies with the crocodile while in water." },
    { text: "अपना हाथ जगन्नाथ।", translation: "Self-help is the best help." },
    { text: "जिसकी लाठी उसकी भैंस।", translation: "Might is right." },
    { text: "लाठी और लालच दोनों पाप के मूल हैं।", translation: "Both force and greed are roots of sin." },
    { text: "सौ सुनार की, एक लोहार की।", translation: "One blow of a blacksmith equals hundred blows of a goldsmith." }
],
"Kannada": [
    { text: "ದುಡಿಮೆಯೇ ದೈವ", translation: "Work is worship." },
    { text: "ಕಷ್ಟಪಟ್ಟರೆ ಫಲ ಸಿಗುತ್ತದೆ", translation: "Hard work pays off." },
    { text: "ಮನಸ್ಸಿದ್ದರೆ ಮಾರ್ಗ", translation: "Where there's a will, there's a way." },
    { text: "ಸತ್ಯಮೇವ ಜಯತೇ", translation: "Truth alone triumphs." },
    { text: "ಅತಿಥಿ ದೇವೋ ಭವ", translation: "The guest is God." },
    { text: "ಕಣ್ಣಿಗೆ ಕಣ್ಣಿಲ್ಲ, ನೋಟಕ್ಕೆ ಮರೆಯಿಲ್ಲ", translation: "Eyes have no curtains, vision has no barriers." },
    { text: "ಹಣ್ಣಾದ ಮರ ಬಗ್ಗುತ್ತದೆ", translation: "A tree laden with fruits bends down." },
    { text: "ಕೈ ಕೆಸರಾದರೆ ಬಾಯಿ ಮೊಸರು", translation: "If hands get muddy, mouth gets buttermilk." },
    { text: "ಹಸಿವಿನಲ್ಲಿ ಹುಳಿ ಸಿಹಿ", translation: "In hunger, even sour tastes sweet." },
    { text: "ಬಂದವರೆಲ್ಲ ಸಂಬಂಧಿ, ಹೋದವರೆಲ್ಲ ದೂರದವರು", translation: "All who come are relatives, all who leave are strangers." },
    { text: "ಮಾತಿಗಿಂತ ಕೃತಿ ಮೇಲು", translation: "Action is better than words." },
    { text: "ಹೊಟ್ಟೆಗೆ ಅನ್ನ, ಮನಸ್ಸಿಗೆ ಜ್ಞಾನ", translation: "Food for stomach, knowledge for mind." },
    { text: "ಬಾಯಿಗೆ ಬಂದದ್ದು ಬಾಗಿಲಿಗೆ ಬರುವುದಿಲ್ಲ", translation: "What comes to mouth doesn't come to the door." },
    { text: "ಕಲಿತವನು ಕಡಲಾಡಿದರೂ ಕಷ್ಟವಿಲ್ಲ", translation: "For the learned, even crossing oceans is not difficult." },
    { text: "ಹಸಿದವನಿಗೆ ಹಣ್ಣು ಹಣ್ಣಲ್ಲ", translation: "For the hungry, fruit is not fruit." },
    { text: "ಹುಟ್ಟಿದವನು ಸಾಯಲೇಬೇಕು", translation: "One who is born must die." },
    { text: "ಕಣ್ಣಿಗೆ ಕಾಣದಿದ್ದರೂ ಮನಸ್ಸಿಗೆ ಕಾಣುತ್ತದೆ", translation: "Though invisible to the eye, it's visible to the mind." },
    { text: "ತಾಳಿದವನು ಬಾಳಿಯಾನು", translation: "He who has patience will survive." },
    { text: "ಉಪ್ಪಿಗಿಂತ ರುಚಿ ಇಲ್ಲ", translation: "There's no taste better than salt." },
    { text: "ಹೊಸದು ಕಂಡರೆ ಹಳೆಯದನ್ನು ಬಿಡಬೇಡ", translation: "Don't abandon the old upon seeing the new." }
],
"Mandarin": [
    { text: "千里之行，始于足下。", translation: "A journey of a thousand miles begins with a single step." },
    { text: "活到老，学到老。", translation: "Live till old, learn till old." },
    { text: "一分耕耘，一分收获。", translation: "You reap what you sow." },
    { text: "三个臭皮匠，顶个诸葛亮。", translation: "Three cobblers with their wits combined equal Zhuge Liang (the master mind)." },
    { text: "不在乎天长地久，只在乎曾经拥有。", translation: "What matters is not how long it lasts, but that it happened." },
    { text: "业精于勤，荒于嬉。", translation: "Diligence is the path to success, play is the path to failure." },
    { text: "机不可失，时不再来。", translation: "Opportunity knocks but once." },
    { text: "人无远虑，必有近忧。", translation: "One who doesn't plan for the future will find trouble at their doorstep." },
    { text: "水滴石穿。", translation: "Dripping water penetrates the stone." },
    { text: "良药苦口利于病，忠言逆耳利于行。", translation: "Good medicine tastes bitter but cures sickness; good advice is hard to hear but beneficial to one's conduct." },
    { text: "一寸光阴一寸金，寸金难买寸光阴。", translation: "An inch of time is an inch of gold, but an inch of gold cannot buy an inch of time." },
    { text: "己所不欲，勿施于人。", translation: "Do not do unto others what you do not want done unto you." },
    { text: "学而不思则罔，思而不学则殆。", translation: "Learning without thought is labor lost; thought without learning is perilous." },
    { text: "千里送鹅毛，礼轻情意重。", translation: "A goose feather sent from a thousand miles away, a small gift may be a token of profound friendship." },
    { text: "画虎画皮难画骨，知人知面不知心。", translation: "It's easy to draw a tiger's skin but not its bones; it's easy to know a person's face but not their heart." },
    { text: "路遥知马力，日久见人心。", translation: "A long journey tests a horse's strength, time reveals a person's heart." },
    { text: "枪打出头鸟。", translation: "The shot hits the bird that pokes its head out." },
    { text: "不经一事，不长一智。", translation: "One cannot grow without experiencing difficulties." },
    { text: "远水救不了近火。", translation: "Distant water cannot put out a nearby fire." },
    { text: "一个萝卜一个坑。", translation: "Every radish has its hole (there's a place for everyone)." }
],
"Arabic": [
    { text: "العلم في الصغر كالنقش على الحجر", translation: "Learning in youth is like engraving on stone." },
    { text: "يد واحدة لا تصفق", translation: "One hand cannot clap." },
    { text: "العقل السليم في الجسم السليم", translation: "A sound mind in a sound body." },
    { text: "الوقت كالسيف إن لم تقطعه قطعك", translation: "Time is like a sword: if you don't cut it, it cuts you." },
    { text: "خير الكلام ما قل ودل", translation: "The best speech is that which is brief and to the point." },
    { text: "الكتاب يقرأ من عنوانه", translation: "A book is read by its title." },
    { text: "رب صدفة خير من ألف ميعاد", translation: "A chance encounter is better than a thousand appointments." },
    { text: "الصديق وقت الضيق", translation: "A friend in need is a friend indeed." },
    { text: "الجار قبل الدار", translation: "The neighbor before the house." },
    { text: "من جد وجد ومن زرع حصد", translation: "Who strives shall succeed, and who sows shall reap." },
    { text: "الحاجة أم الاختراع", translation: "Necessity is the mother of invention." },
    { text: "العين بصيرة واليد قصيرة", translation: "The eye sees but the hand can't reach." },
    { text: "القناعة كنز لا يفنى", translation: "Contentment is a treasure that does not perish." },
    { text: "اسأل مجرب ولا تسأل طبيب", translation: "Ask someone with experience rather than a doctor." },
    { text: "الصبر مفتاح الفرج", translation: "Patience is the key to relief." },
    { text: "لكل جواد كبوة", translation: "Every horse has a stumble." },
    { text: "من شب على شيء شاب عليه", translation: "What one learns in youth is carved in stone." },
    { text: "العلم نور والجهل ظلام", translation: "Knowledge is light and ignorance is darkness." },
    { text: "كل إناء بما فيه ينضح", translation: "Every vessel exudes what it contains." },
    { text: "رب كلمة تقول لصاحبها دعني", translation: "Many a word would say to its utterer: leave me." }
]
    
        // More languages will follow in the next parts
    }
};